"""update image table

Revision ID: 670c3d0c4bae
Revises: 4afb3c4e3398
Create Date: 2026-02-19 00:31:00.896425

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '670c3d0c4bae'
down_revision: Union[str, Sequence[str], None] = '4afb3c4e3398'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('file_path', sa.String(), nullable=False))
    op.drop_column('images', 'data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False))
    op.drop_column('images', 'file_path')
    # ### end Alembic commands ###
